### ISSUE TITLE
wrong output in mi_calculate.py 

### ISSUE THREAD

**Issue by T2shen** [xydaytoy/BMI-NMT#2]
I train your model on LDC zh-en dataset and observe a BLEU decline on NIST test set.  This may be caused by the wrong  BMI score produced by mi_calculate.py.  It just outputs a single BMI score for each sentence.  In line 82, what you write should be "str_weight" rather than "weight".

**Comment by xydaytoy** [comment]
@T2shen 
It should be “str_weight” in line 82, I'll correct it. Thank you for your help.
